"""
netrun.py -- Network intrusion.

THE TRACE MODEL
    Trace is a 0-100 meter that persists BETWEEN runs. It does not reset when
    you jack out; it decays slowly over world turns. This is the central
    tension of netrunning: every run you make raises a clock that follows you
    back into meatspace.

        0-24     Clean      -- nothing
        25-49    Flagged    -- CRA encounter weight rises
        50-74    Tracked    -- hostile runners may counter-dive you
        75-94    Pinned     -- a strike team is being dispatched
        95-100   Burned     -- they have your address. They come.

    Trace rises from: each node action (base), ICE trace_rate on detection,
    failed intrusion checks. It falls from: the Veil program (negative trace),
    coolant shunts, Cauterise, and time.

RUNNING A HOST
    A host is a linear stack of nodes generated by worldgen.generate_net_host.
    At each node the runner may:
        probe   -- read what's there without engaging (small trace)
        crack   -- intrusion check to take the node (medium trace)
        attack  -- fight the ICE with an attack program
        stealth -- bypass the ICE entirely (hard check, low trace)
        pull    -- extract the node's payload once cracked
        jack    -- leave, keeping everything extracted so far

DECK BUFFER AS HIT POINTS
    ICE attacks deplete the deck's buffer. When buffer hits zero, further ICE
    damage carries through the neural port into the runner as real HP damage,
    and LETHAL ICE degrades cyberware on every hit. A cheap deck is not just
    slower -- it is the only thing between your brain and a Verdict.
"""

from __future__ import annotations

import sqlite3

from . import content
from .db import Database, jdump, jload
from .dice import Dice
from .rules import Character, adjust_heat, adjust_rep

TRACE_BANDS = [
    (95, "Burned"), (75, "Pinned"), (50, "Tracked"), (25, "Flagged"), (0, "Clean"),
]


def trace_band(value: int) -> str:
    for threshold, label in TRACE_BANDS:
        if value >= threshold:
            return label
    return "Clean"


class NetRun:
    """One dive into one host."""

    def __init__(self, db: Database, dice: Dice, char: Character, host_id: int):
        self.db = db
        self.dice = dice
        self.char = char
        self.host = db.one("SELECT * FROM net_hosts WHERE id=?", (host_id,))
        if not self.host:
            raise ValueError(f"no host {host_id}")

        props = jload(self.host["props"], {})
        self.nodes: list[dict] = props.get("nodes", [])
        self.position = 0
        self.log: list[str] = []
        self.jacked_out = False
        self.extracted: list[dict] = []
        self.cauterise_used = False

        deck = char.equipped_deck()
        if deck:
            tmpl = content.DECKS[deck["template"]]
            self.deck_row = deck
            self.buffer = tmpl["buffer"]
            self.buffer_max = tmpl["buffer"]
            self.shield = tmpl["shield"]
            self.speed = tmpl["speed"]
        else:
            self.deck_row = None
            self.buffer = self.buffer_max = self.shield = self.speed = 0

        # Current ICE engagement, if any.
        self.active_ice: dict | None = None

    # ------------------------------------------------------------------
    def emit(self, text: str) -> None:
        self.log.append(text)

    def drain_log(self) -> list[str]:
        out = self.log[:]
        self.log = []
        return out

    @property
    def node(self) -> dict | None:
        if 0 <= self.position < len(self.nodes):
            return self.nodes[self.position]
        return None

    def finished(self) -> bool:
        return (
            self.jacked_out
            or self.char.is_dead()
            or self.position >= len(self.nodes)
        )

    # ------------------------------------------------------------------
    # TRACE
    # ------------------------------------------------------------------
    def add_trace(self, amount: int, source: str = "") -> None:
        """
        Raise (or lower) trace. Veil is applied as a flat reduction to any
        positive accumulation while it is in the runner's program loadout.
        """
        if amount > 0 and self._has_program("prog_veil"):
            amount = max(0, amount + content.PROGRAMS["prog_veil"]["trace"] // 2)

        before = self.char.row["trace"]
        new = self.db.adjust_player("trace", amount, lo=0, hi=100)
        if trace_band(new) != trace_band(before):
            self.emit(f"*** TRACE {new} -- {trace_band(new).upper()} ***")
            self.db.log(f"Trace escalated to {trace_band(new)} ({new}).", "trace")
        elif amount:
            self.emit(f"Trace {new} ({trace_band(new)}).")

    def _has_program(self, key: str) -> bool:
        return any(p["template"] == key for p in self.char.programs())

    def _program(self, key: str) -> sqlite3.Row | None:
        for p in self.char.programs():
            if p["template"] == key:
                return p
        return None

    def attack_programs(self) -> list[sqlite3.Row]:
        return [
            p for p in self.char.programs()
            if content.PROGRAMS.get(p["template"], {}).get("class") == "attack"
        ]

    # ------------------------------------------------------------------
    # ACTIONS
    # ------------------------------------------------------------------
    def probe(self) -> None:
        """Look before you touch. Cheap in trace, reveals the node's defences."""
        n = self.node
        if not n:
            return
        chk = self.char.check("signal", difficulty="easy", deck=self.speed)
        self.add_trace(2, "probe")
        if not chk.success:
            self.emit("The probe comes back garbled. You learn nothing useful.")
            return
        ice_key = n.get("ice")
        if ice_key:
            spec = content.ICE[ice_key]
            lethal = "  *** BLACK ICE -- LETHAL ***" if spec["lethal"] else ""
            self.emit(
                f"Node {self.position + 1}: {n['label']}. "
                f"Guarded by {spec['name']} "
                f"(atk {spec['attack']}, def {spec['defense']}, "
                f"{spec['hp']} integrity).{lethal}"
            )
        else:
            self.emit(f"Node {self.position + 1}: {n['label']}. Undefended.")
        if "ice_read" in self.char.grants():
            self.emit(f"Cortex stack reads payload: {n['payload']['kind']}.")

    def crack(self) -> None:
        """
        Take the node by direct intrusion. If ICE is present and not yet
        destroyed, it engages first.
        """
        n = self.node
        if not n:
            return
        if n.get("ice") and not n.get("ice_down"):
            self.emit(f"{content.ICE[n['ice']]['name']} blocks the attempt.")
            self._ice_strike(n["ice"])
            return

        dv = 12 + self.host["tier"] * 2 + self.position
        chk = self.char.check("intrusion", difficulty=dv, deck=self.speed)
        if chk.success:
            n["cracked"] = True
            self._persist()
            self.add_trace(4, "crack")
            self.emit(f"Node {self.position + 1} is yours. ({chk.describe()})")
            if chk.critical:
                self.emit("Clean entry. No log written.")
                self.db.adjust_player("trace", -4, lo=0)
        else:
            self.add_trace(9 + abs(chk.margin) // 3, "failed crack")
            self.emit(f"Rejected. ({chk.describe()})")
            if n.get("ice") and not n.get("ice_down"):
                self._ice_strike(n["ice"])

    def stealth_past(self) -> None:
        """
        Slip the node without cracking it. Hard, but almost trace-free -- and
        you forfeit the payload. The route for runners who want depth, not loot.
        """
        n = self.node
        if not n:
            return
        dv = 16 + self.host["tier"] * 2 + self.position
        chk = self.char.check("evasion", difficulty=dv, deck=self.speed)
        if chk.success:
            self.add_trace(1, "stealth")
            self.emit(f"You move through node {self.position + 1} without touching it.")
            self.position += 1
        else:
            self.add_trace(12, "failed stealth")
            self.emit("You brush a tripwire.")
            if n.get("ice") and not n.get("ice_down"):
                self._ice_strike(n["ice"])

    def attack_ice(self, program_key: str) -> None:
        """Break ICE with an attack program."""
        n = self.node
        if not n or not n.get("ice") or n.get("ice_down"):
            self.emit("Nothing to break here.")
            return

        prog = self._program(program_key)
        if not prog:
            self.emit("You don't have that program loaded.")
            return
        pspec = content.PROGRAMS[program_key]
        ice_key = n["ice"]
        ispec = content.ICE[ice_key]

        n.setdefault("ice_hp", ispec["hp"])

        chk = self.char.check(
            "intrusion", difficulty=10 + ispec["defense"],
            program=pspec["power"], deck=self.speed,
        )
        self.add_trace(pspec["trace"], f"{pspec['name']}")

        if chk.success:
            dmg = pspec["power"] + self.dice.d6() + chk.margin // 3
            n["ice_hp"] -= dmg
            self.emit(f"{pspec['name']} lands for {dmg}. "
                      f"{ispec['name']} at {max(0, n['ice_hp'])}/{ispec['hp']}.")
            if n["ice_hp"] <= 0:
                n["ice_down"] = True
                self.emit(f"{ispec['name']} is destroyed.")
                self.char.award_xp(15 * ispec["tier"])
        else:
            self.emit(f"{pspec['name']} glances off.")

        self._persist()
        self._ice_strike(ice_key)

    def pull(self) -> None:
        """Extract the payload from a cracked node."""
        n = self.node
        if not n:
            return
        if not n.get("cracked"):
            self.emit("Node isn't cracked.")
            return
        if n.get("pulled"):
            self.emit("Already stripped.")
            return

        payload = n["payload"]
        siphon = self._has_program("prog_siphon")
        mult = 1.5 if siphon else 1.0
        self.add_trace(3 if siphon else 6, "extraction")

        kind = payload["kind"]
        if kind == "credits":
            amount = int(payload["amount"] * mult)
            self.char.credits(amount)
            self.emit(f"Pulled {amount}cr.")
        elif kind == "data":
            value = int(payload["value"] * mult)
            self.db.bump_flag("data_shards", 1)
            self.char.credits(value)
            self.emit(f"Pulled a data shard. Sold on the spot for {value}cr.")
        elif kind == "program":
            self.char.give_item(payload["key"])
            self.emit(f"Recovered program: {content.PROGRAMS[payload['key']]['name']}.")
        elif kind == "intel":
            self.db.bump_flag("intel_fragments", 1)
            self.emit("Recovered an intel fragment. Someone will want this.")
            self.db.log("Recovered an intel fragment.", "quest")
        elif kind == "control":
            self.db.set_flag(f"control_{self.host['id']}", True)
            self.emit("You now hold physical security control for this facility.")
        else:
            self.emit("Empty. Someone got here first.")

        n["pulled"] = True
        self.extracted.append(payload)
        self._persist()

    def descend(self) -> None:
        n = self.node
        if n and n.get("ice") and not n.get("ice_down") and not n.get("cracked"):
            self.emit("The ICE won't let you past.")
            self._ice_strike(n["ice"])
            return
        self.position += 1
        if self.position >= len(self.nodes):
            self.emit("You're through the whole stack. Nothing deeper.")
            self.db.run("UPDATE net_hosts SET cracked=1 WHERE id=?", (self.host["id"],))
        else:
            self.emit(f"Descending to node {self.position + 1}.")

    def cauterise(self) -> None:
        prog = self._program("prog_cauterise")
        if not prog or self.cauterise_used:
            self.emit("Cauterise is unavailable.")
            return
        self.cauterise_used = True
        self.db.adjust_player("trace", -content.PROGRAMS["prog_cauterise"]["power"], lo=0)
        self.emit(f"Cauterise fires. Trace dumped to {self.char.row['trace']}.")

    def jack_out(self) -> None:
        self.jacked_out = True
        self.emit("You jack out.")
        # Leaving under high trace is itself dangerous.
        trace = self.char.row["trace"]
        if trace >= 75:
            adjust_heat(self.db, self.char.row["district"], 15)
            self.emit("You came out hot. Somebody logged the exit point.")

    # ------------------------------------------------------------------
    # ICE BEHAVIOUR
    # ------------------------------------------------------------------
    def _ice_strike(self, ice_key: str) -> None:
        """
        ICE retaliates. Damage hits deck buffer first, then the runner.
        Mirror reflects a portion back.
        """
        spec = content.ICE[ice_key]
        self.add_trace(spec["trace_rate"], spec["name"])

        chk = self.dice.check(
            attribute=spec["attack"], skill=spec["tier"],
            difficulty=10 + self.char.attr("WIR") + self.char.skill("evasion"),
        )
        if not chk.success:
            self.emit(f"{spec['name']} strikes and misses.")
            return

        dmg = spec["attack"] + self.dice.d6() + chk.margin // 4
        dmg = max(1, dmg - self.shield)

        if self._has_program("prog_mirror"):
            reflected = content.PROGRAMS["prog_mirror"]["power"]
            node = self.node
            if node:
                node.setdefault("ice_hp", spec["hp"])
                node["ice_hp"] -= reflected
                self.emit(f"Mirror reflects {reflected} back into {spec['name']}.")
                if node["ice_hp"] <= 0:
                    node["ice_down"] = True
                    self.emit(f"{spec['name']} collapses under its own attack.")
                self._persist()

        if self.buffer > 0:
            absorbed = min(self.buffer, dmg)
            self.buffer -= absorbed
            dmg -= absorbed
            self.emit(f"{spec['name']} hits for {absorbed} -- buffer "
                      f"{self.buffer}/{self.buffer_max}.")
            if self.buffer == 0:
                self.emit("*** BUFFER GONE. Damage is coming through the port. ***")
            if self.deck_row and self.dice.chance(0.25):
                self.db.run(
                    "UPDATE items SET condition=MAX(0,condition-3) WHERE id=?",
                    (self.deck_row["id"],),
                )

        if dmg > 0:
            # Feedback into meat. Only HALF of the overflow crosses the neural
            # port -- at full carry-through, a tier-4 host killed a fully
            # equipped Runner in roughly two thirds of dives, which made black
            # ICE a coin flip on the character rather than a risk to manage.
            dmg = max(1, dmg // 2)
            taken, notices = self.char.damage(dmg, bypass_armor=True, source=spec["name"])
            self.emit(f"FEEDBACK: {taken} damage through the neural port.")
            for n in notices:
                self.emit(n)
            if spec["lethal"]:
                for msg in self.char.degrade_cyberware(self.dice.between(6, 14)):
                    self.emit(msg)
                if self.dice.chance(0.2):
                    self.char.add_status("stunned", turns=1, source="black ice")
                    self.emit("Your hands stop responding for a moment.")

    def _persist(self) -> None:
        """Write node state back to the host row so progress survives a jackout."""
        props = jload(self.host["props"], {})
        props["nodes"] = self.nodes
        self.db.run(
            "UPDATE net_hosts SET props=? WHERE id=?",
            (jdump(props), self.host["id"]),
        )

    # ------------------------------------------------------------------
    def finish(self) -> list[str]:
        """Consequences of the run, applied once on exit."""
        out = []
        owner = self.host["owner"]
        pulled = [n for n in self.nodes if n.get("pulled")]
        if pulled and owner:
            loss = -2 * len(pulled)
            adjust_rep(self.db, owner, loss)
            out.append(f"{content.FACTIONS[owner]['name']} noticed. "
                       f"Standing {loss}.")
        if pulled:
            xp = 20 * len(pulled)
            out += self.char.award_xp(xp)
            out.append(f"+{xp} XP from the run.")
        if self.char.equipped_deck() and self.dice.chance(0.3):
            for msg in self.char.degrade_cyberware(self.dice.between(1, 4)):
                out.append(msg)
        return out


# ==========================================================================
# WORLD-LEVEL TRACE CONSEQUENCES
# ==========================================================================
def decay_trace(db: Database, char: Character) -> None:
    """
    Called once per world turn. Trace bleeds off faster for Runners.
    Above Pinned, trace also converts into district heat.
    """
    rate = 5 if char.passive() == "trace_shed" else 2
    trace = char.row["trace"]
    if trace > 0:
        db.adjust_player("trace", -rate, lo=0)
    if trace >= 75:
        adjust_heat(db, char.row["district"], 4)


def trace_consequence(db: Database, dice: Dice, char: Character) -> str | None:
    """
    At Burned trace, a strike team may arrive. Returns an encounter key or
    None. Called by the world tick.
    """
    trace = char.row["trace"]
    if trace >= 95 and dice.chance(0.4):
        db.adjust_player("trace", -30, lo=0)
        return "strike_team"
    if trace >= 75 and dice.chance(0.15):
        return "counter_dive"
    return None
